info:
  app:
    name: IAM Service App
    description: IAM Service with Spring Boot, PostgresSQL and JWT

server:
  port: 8081

keycloak:
  enabled: false
  realm: IAMService
  auth-server-url: http://localhost:8080
  client:
    id: iam-service-api
    secret: lkbRJLrdzVuIr47DQJfBwmiXzbA6hdkJ
  admin:
    username: theanh
    password: theanh

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/iam-2
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    auditor-aware-ref: auditorAwareImp
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/IAMService
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs

redis:
  host: localhost
  port: 6379